### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/Halma#8]
It would be awesome if we could support the web (additionally to Android). 
Windows, Linux, macOS and iOS are **not** needed because the web version would work on all those platforms as well.

**Comment by CrazyMarvin** [comment]
I am not sure if we need a [root](https://hetzner.cloud) [VPS](https://m.do.co/c/d4e804717547) or if a simple web space like [GitHub Pages](https://pages.github.com/) or a [shared hos](https://www.namecheap.com/hosting/shared/)[ting package](https://billing.flokinet.is/aff.php?aff=46
) would be better. 🤔
This depends strongly on #6 I suppose. When we need to host the online multiplayer part on a root VPS, we simply could use it to serve the game too. If the online multiplayer is handled by a cloud service, then a simple web space might be enough.

**Comment by Frosty-J** [comment]
I think GitHub Pages would be good enough, unless implementing online multiplayer. It can use the halma.app domain. Shared hosting can be both pricey and slow - I don't see what benefit that has over GitHub Pages. I'm also familiar with pushing builds to itch.io and my own VPS using GitHub Actions.

Nice referral link. I have a chunk of leftover DigitalOcean credit since I switched hosts and I don't know what to do with it. It's nice to be able to spin up temporary servers without it coming out my bank balance, though.

**Comment by CrazyMarvin** [comment]
It would be awesome if you could setup GitHub Actions to publish the game on GitHub Pages and itch.io. 👍

**Comment by CrazyMarvin** [comment]
I already started but it is not functional yet:
[GitHub Pages](https://github.com/Crazy-Marvin/Halma/blob/development/.github/workflows/deploy_pages.yml)
[itch.io](https://github.com/Crazy-Marvin/Halma/blob/development/.github/workflows/deploy_itch.yml)

**Comment by CrazyMarvin** [comment]
Are you able to work on this next month, @Frosty-J?

**Comment by Frosty-J** [comment]
Probably. Have you created an itch.io account yet?

**Comment by CrazyMarvin** [comment]
> Probably. Have you created an itch.io account yet?

That are great news.
Yes, I already have an itch.io account and [a page for the game](https://crazy-marvin.itch.io/halma).
